# Multistage build for Golang application

# Stage 1: Build the application
FROM arm64v8/golang:1.22-bullseye AS go-builder

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y git make

WORKDIR /go/src/app

# 소스 코드 복사
COPY . .

# 빌드 명령어
RUN go mod download
RUN go build -o build/initiad ./cmd/initiad

# Stage 2: Create the runtime image
FROM arm64v8/ubuntu:20.04

WORKDIR /root

# 빌드된 바이너리와 라이브러리 복사
COPY --from=go-builder /go/src/app/build/initiad /usr/local/bin/initiad

CMD ["initiad"]
