name: Build ARM64
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set environment variables
        run: |
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "GOOS=linux" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${GITHUB_SHA}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build for ARM64
        run: |
          docker run --rm --privileged --platform linux/arm64 \
            -v $(pwd):/go/src/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /go/src/app \
            -e GOARCH -e GOOS -e VERSION \
            arm64v8/golang:1.22.4 \
            sh -c "
              git config --global --add safe.directory /go/src/app
              export GOARCH=${GOARCH}
              export GOOS=${GOOS}
              go mod download
              apt-get update && apt-get install -y make docker.io
              service docker start
              make build-linux-with-shared-library
              cd ./build
              mkdir -p initia_${VERSION}
              if [ -f libmovevm.so ]; then mv libmovevm.so initia_${VERSION}/libmovevm.${GOARCH}.so; fi
              if [ -f libcompiler.so ]; then mv libcompiler.so initia_${VERSION}/libcompiler.${GOARCH}.so; fi
              if [ -f initiad ]; then mv initiad initia_${VERSION}/; fi
              tar -czvf initia_${VERSION}_Linux_${GOARCH}.tar.gz initia_${VERSION}
              mv initia_${VERSION}_Linux_${GOARCH}.tar.gz /go/src/app/
            "

      - name: List files
        run: |
          ls -l
          ls -l ./build || echo "Build directory not found"

      # ... (나머지 단계는 그대로 유지)
