

name: Build and Upload to GCS

on:
  # push:
  #   tags:
  #     - 'v*'
  push:
    branches:
      - "main"
      
jobs:
  # build-linux-amd64:
  #   uses: ./.github/workflows/build-linux.yml
  #   with:
  #     arch: amd64
  #   secrets: inherit

  # build-linux-arm64:
  #   uses: ./.github/workflows/build-linux.yml
  #   with:
  #     arch: arm64
  #   secrets: inherit

  build-darwin-amd64:
    uses: ./.github/workflows/build-darwin.yml
    with:
      arch: amd64
    secrets: inherit

  build-darwin-arm64:
    uses: ./.github/workflows/build-darwin.yml
    with:
      arch: arm64
    secrets: inherit
