name: Build Darwin ARM64
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
      - name: Set environment variables
        run: |
          echo "GOARCH=${{ inputs.arch }}" >> $GITHUB_ENV
          echo "GOOS=darwin" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
          echo "MOVEVM_VERSION=v0.2.15" >> $GITHUB_ENV
      - name: Ensure dependencies
        run: |
          go mod tidy
          go get github.com/initia-labs/movevm@${MOVEVM_VERSION}
      - name: Print environment variables
        run: |
          echo "GOARCH=${GOARCH}"
          echo "GOOS=${GOOS}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "MOVEVM_VERSION=${MOVEVM_VERSION}"
      - name: Build for Darwin ARM64
        run: |
          export GOARCH=${GOARCH}
          export GOOS=${GOOS}
          go build -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=initia -X github.com/cosmos/cosmos-sdk/version.AppName=initiad -X github.com/cosmos/cosmos-sdk/version.Version=${GITHUB_SHA} -X github.com/cosmos/cosmos-sdk/version.Commit=${GITHUB_SHA} -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cometbft/cometbft/version.TMCoreSemVer=v0.0.0-20240704071957-c46468756c01 -w -s' -trimpath -o build/initiad ./cmd/initiad
          cd ./build
          mkdir -p initia_build
          cp ~/go/pkg/mod/github.com/initia-labs/movevm@${MOVEVM_VERSION}/api/libmovevm.dylib initia_build/libmovevm.${GOARCH}.dylib
          cp ~/go/pkg/mod/github.com/initia-labs/movevm@${MOVEVM_VERSION}/api/libcompiler.dylib initia_build/libcompiler.${GOARCH}.dylib
          mv initiad initia_build/
          tar -czvf initia_Darwin_${GOARCH}.tar.gz initia_build
      # ... 나머지 단계는 그대로 유지 ...
