# name: Build ARM64

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build Docker image for ARM64
#         run: |
#           docker build --platform linux/arm64 --build-arg GOARCH=arm64 -t myapp:arm64 -f .github/workflows/Dockerfile.arm .

#       - name: Google Auth
#         uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: Set up Cloud SDK
#         uses: 'google-github-actions/setup-gcloud@v2'

#       - name: Upload to GCS
#         env:
#           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
#         run: |
#           docker save myapp:arm64 | gzip > myapp_arm64.tar.gz
#           gsutil cp myapp_arm64.tar.gz gs://${GCS_BUCKET}/

#       - name: Verify upload and Generate public URL
#         env:
#           GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
#         run: |
#           if gsutil stat gs://${GCS_BUCKET}/myapp_arm64.tar.gz; then
#             echo "File successfully uploaded"
#             echo "Public URL: https://storage.googleapis.com/${GCS_BUCKET}/myapp_arm64.tar.gz" >> $GITHUB_STEP_SUMMARY
#           else
#             echo "File upload failed"
#             exit 1
#           fi
