# 1단계: 빌드 스테이지
FROM arm64v8/golang:1.20.4 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 모듈 캐시를 사용하여 종속성 다운로드
COPY go.mod go.sum ./
RUN go mod download

# 소스 코드 복사
COPY . .

# ARM 아키텍처로 빌드 수행
RUN GOARCH=arm64 GOOS=linux CGO_ENABLED=1 go build -o build/initiated .

# 2단계: 런타임 스테이지
FROM arm64v8/alpine:latest

# 작업 디렉토리 설정
WORKDIR /app

# 빌드 스테이지에서 빌드된 바이너리 복사
COPY --from=builder /app/build/initiated .

# 엔트리포인트 설정
ENTRYPOINT ["./initiated"]
