# 1단계: 빌드 스테이지
FROM --platform=linux/arm64 golang:1.22.4 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 모듈 캐시를 복사하고 의존성 설치
COPY go.mod go.sum ./
RUN go mod download

# 소스 코드 복사
COPY . .

# ARM 아키텍처로 빌드 수행
RUN GOARCH=$GOARCH GOOS=$GOOS CGO_ENABLED=1 go build -o build/initiated .

# 2단계: 런타임 스테이지
FROM --platform=linux/arm64 arm64v8/alpine:latest

# 작업 디렉토리 설정
WORKDIR /root/

# 빌드 단계에서 생성된 바이너리 파일 복사
COPY --from=builder /app/build/initiated .

# 실행할 기본 명령어 설정
CMD ["./initiated"]
